// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using kolokwium2F.DAL;

#nullable disable

namespace kolokwium2F.Migrations
{
    [DbContext(typeof(GalleriesDbContext))]
    partial class GalleriesDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("kolokwium2F.Models.Artist", b =>
                {
                    b.Property<int>("ArtistId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ArtistId"));

                    b.Property<DateTime>("BirthDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("ArtistId");

                    b.ToTable("Artist");

                    b.HasData(
                        new
                        {
                            ArtistId = 1,
                            BirthDate = new DateTime(2025, 7, 10, 20, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "k",
                            LastName = "A"
                        },
                        new
                        {
                            ArtistId = 2,
                            BirthDate = new DateTime(2025, 7, 15, 19, 30, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "a",
                            LastName = "B"
                        },
                        new
                        {
                            ArtistId = 3,
                            BirthDate = new DateTime(2025, 8, 1, 18, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "b",
                            LastName = "C"
                        });
                });

            modelBuilder.Entity("kolokwium2F.Models.Artwork", b =>
                {
                    b.Property<int>("ArtworkId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ArtworkId"));

                    b.Property<int>("ArtistId")
                        .HasColumnType("int");

                    b.Property<int>("InsuranceValue")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("YearCreated")
                        .HasColumnType("int");

                    b.HasKey("ArtworkId");

                    b.ToTable("Artwork");

                    b.HasData(
                        new
                        {
                            ArtworkId = 1,
                            ArtistId = 0,
                            InsuranceValue = 0,
                            Title = "AB-001",
                            YearCreated = 2010
                        },
                        new
                        {
                            ArtworkId = 2,
                            ArtistId = 0,
                            InsuranceValue = 0,
                            Title = "AB-002",
                            YearCreated = 2002
                        },
                        new
                        {
                            ArtworkId = 3,
                            ArtistId = 0,
                            InsuranceValue = 0,
                            Title = "CD-001",
                            YearCreated = 2015
                        },
                        new
                        {
                            ArtworkId = 4,
                            ArtistId = 0,
                            InsuranceValue = 0,
                            Title = "EF-001",
                            YearCreated = 2025
                        });
                });

            modelBuilder.Entity("kolokwium2F.Models.Exhibition", b =>
                {
                    b.Property<int>("ExhibitionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ExhibitionId"));

                    b.Property<DateTime?>("EndDate")
                        .IsRequired()
                        .HasColumnType("datetime2");

                    b.Property<int>("GalleryId")
                        .HasColumnType("int");

                    b.Property<int>("NumberOfArtworks")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("ExhibitionId");

                    b.HasIndex("GalleryId");

                    b.ToTable("Exhibition");

                    b.HasData(
                        new
                        {
                            ExhibitionId = 1,
                            EndDate = new DateTime(2025, 7, 10, 20, 0, 0, 0, DateTimeKind.Unspecified),
                            GalleryId = 1,
                            NumberOfArtworks = 2,
                            StartDate = new DateTime(2025, 6, 1, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "AB-001"
                        },
                        new
                        {
                            ExhibitionId = 2,
                            EndDate = new DateTime(2025, 7, 10, 20, 0, 0, 0, DateTimeKind.Unspecified),
                            GalleryId = 2,
                            NumberOfArtworks = 2,
                            StartDate = new DateTime(2025, 6, 1, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Ac-001"
                        },
                        new
                        {
                            ExhibitionId = 3,
                            EndDate = new DateTime(2025, 7, 10, 20, 0, 0, 0, DateTimeKind.Unspecified),
                            GalleryId = 3,
                            NumberOfArtworks = 2,
                            StartDate = new DateTime(2025, 6, 1, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "As-001"
                        },
                        new
                        {
                            ExhibitionId = 4,
                            EndDate = new DateTime(2025, 7, 10, 20, 0, 0, 0, DateTimeKind.Unspecified),
                            GalleryId = 4,
                            NumberOfArtworks = 2,
                            StartDate = new DateTime(2025, 6, 1, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Aq-001"
                        });
                });

            modelBuilder.Entity("kolokwium2F.Models.ExhibitionArtwork", b =>
                {
                    b.Property<int>("ExhibitionId")
                        .HasColumnType("int");

                    b.Property<int>("ArtworkId")
                        .HasColumnType("int");

                    b.Property<int>("GalleryId")
                        .HasColumnType("int");

                    b.Property<decimal>("InsuranceValue")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("ExhibitionId");

                    b.HasIndex("ArtworkId")
                        .IsUnique();

                    b.HasIndex("GalleryId");

                    b.ToTable("ExhibitionArtwork");

                    b.HasData(
                        new
                        {
                            ExhibitionId = 1,
                            ArtworkId = 1,
                            GalleryId = 0,
                            InsuranceValue = 2m
                        },
                        new
                        {
                            ExhibitionId = 2,
                            ArtworkId = 2,
                            GalleryId = 0,
                            InsuranceValue = 2m
                        },
                        new
                        {
                            ExhibitionId = 4,
                            ArtworkId = 3,
                            GalleryId = 0,
                            InsuranceValue = 2m
                        });
                });

            modelBuilder.Entity("kolokwium2F.Models.Gallery", b =>
                {
                    b.Property<int>("GalleryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("GalleryId"));

                    b.Property<DateTime>("EstablishedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("GalleryId");

                    b.ToTable("Gallery");

                    b.HasData(
                        new
                        {
                            GalleryId = 1,
                            EstablishedDate = new DateTime(2025, 7, 10, 20, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "A"
                        },
                        new
                        {
                            GalleryId = 2,
                            EstablishedDate = new DateTime(2025, 7, 10, 20, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "J"
                        },
                        new
                        {
                            GalleryId = 3,
                            EstablishedDate = new DateTime(2025, 7, 10, 20, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "P"
                        });
                });

            modelBuilder.Entity("kolokwium2F.Models.Exhibition", b =>
                {
                    b.HasOne("kolokwium2F.Models.Gallery", null)
                        .WithMany("Artworks")
                        .HasForeignKey("GalleryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("kolokwium2F.Models.ExhibitionArtwork", b =>
                {
                    b.HasOne("kolokwium2F.Models.Artwork", null)
                        .WithOne("ExhibitionArtwork")
                        .HasForeignKey("kolokwium2F.Models.ExhibitionArtwork", "ArtworkId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("kolokwium2F.Models.Exhibition", null)
                        .WithOne("Artwork")
                        .HasForeignKey("kolokwium2F.Models.ExhibitionArtwork", "ExhibitionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("kolokwium2F.Models.Gallery", "Gallery")
                        .WithMany()
                        .HasForeignKey("GalleryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Gallery");
                });

            modelBuilder.Entity("kolokwium2F.Models.Artwork", b =>
                {
                    b.Navigation("ExhibitionArtwork")
                        .IsRequired();
                });

            modelBuilder.Entity("kolokwium2F.Models.Exhibition", b =>
                {
                    b.Navigation("Artwork")
                        .IsRequired();
                });

            modelBuilder.Entity("kolokwium2F.Models.Gallery", b =>
                {
                    b.Navigation("Artworks");
                });
#pragma warning restore 612, 618
        }
    }
}
